import './globals.css'
import { oswald, sourceSans3 } from './fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sourceSans3.variable} ${oswald.variable}`}>
      <body className='overflow-auto'>{children}</body>
    </html>
  )
}
